### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7694: character maps to <undefined>

### ISSUE THREAD

**Issue by Jormund** [xificurk/iitc-plugins#1]
I've run the script on Windows 10 using: 
`C:\Users\xxx\rgpd>C:\Users\xxx\AppData\Local\Programs\Python\Python37\python.exe game_log_parser.py game_log.tsv > output.txt`

And got this output:

```
Traceback (most recent call last):
  File "game_log_parser.py", line 66, in <module>
    parse_game_log(game_log_path)
  File "game_log_parser.py", line 45, in parse_game_log
    line = fp.readline().rstrip("\n")
  File "C:\Users\Etienne\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7694: character maps to <undefined>
```

I am not a python expert but I could fix the issue using the following code
`with open(game_log_path, 'r', encoding="utf-8") as fp:`
on line 28 (replacing `with open(game_log_path) as fp:`)

**Comment by xificurk** [comment]
Thank you, I applied the fix you suggested.
